### ISSUE TITLE
database migrations should be commited in git

### ISSUE THREAD

**Issue by xrmx** [mmohrhard/crash#2]
https://docs.djangoproject.com/en/1.9/topics/migrations/#version-control

**Comment by mmohrhard** [comment]
The plan is to do that when the models become more stable. I'm still removing the migrations from time to time as the migrations are causing issues.

As soon as the feature is merged to LibreOffice and we are starting to use it on a server we surely need to store the migrations.

**Comment by mmohrhard** [comment]
Starting with f9c86fed7939cd02ec1c537b56278f7f0318c7a3 migrations are now stored in git. We are setting up a production server so we now need to pay more attention to migrations.
