### ISSUE TITLE
Add search for crash report based on crash id

### ISSUE THREAD

**Issue by mmohrhard** [mmohrhard/crash#20]

**Comment by mmohrhard** [comment]
Each crash report has a unique id that can be used to identify the report. We should provide a search box in the header bar where you can add the ID and will be directly transferred to the correct crash page.

The template that defines the header bar is in https://github.com/mmohrhard/crash/blob/master/django/crashreport/stats/templates/stats/base.html and the unique ID is https://github.com/mmohrhard/crash/blob/master/django/crashreport/processor/models.py#L164.

The URL fragment for a crash is https://github.com/mmohrhard/crash/blob/master/django/crashreport/stats/urls.py#L13 which already expects a crash id.

The search functionality can be quite simple and does not need to do more for now that transfer to the correct crash page or tell the user that no such report exists. In the future we might need an additional step if the report has been uploaded already but not processed yet.

**Comment by an0o0nym** [comment]
I'd like to try to fix that one.

**Comment by mmohrhard** [comment]
Great. Do you need any help from me?

**Comment by an0o0nym** [comment]
I will let you know if I have any problems. Thanks
