### ISSUE TITLE
reflect bug status (unresolved / resolved) on crash stats page

### ISSUE THREAD

**Issue by foss-** [mmohrhard/crash#26]
It would be very useful, to reflect if a bug is already fixed or still unfixed.

Suggestion:

Fixed bugs: tdf#100681 should be strikethrough
Unfixed: normal font

**Comment by mmohrhard** [comment]
Mostly fixed as can be seen at http://crashreport.libreoffice.org/stats/signature/SwTransferable::PrivatePaste(SwWrtShell%20&)#bugs

Commits:
https://github.com/mmohrhard/crash/commit/03867002faf9afbc3deacaf822899c269c0b6065
https://github.com/mmohrhard/crash/commit/b9bac17c43dc0a56abbb659518fe9ae5a7464903

We still need a script that updates the bug report info as part of a cron job. Currently I need to do this manually.

**Comment by mmohrhard** [comment]
Now also the script has been implemented.

Commit:
https://github.com/mmohrhard/crash/commit/48c9a61a377d17081a6ac7651a8720bc78597861

The script is running hourly a minute after the script that updates the connection of bug reports to crash reports. That way we can be sure that any bug report is already stored in the db.
