### ISSUE TITLE
add time ranges to quickly adjust the main view of the crash website

### ISSUE THREAD

**Issue by foss-** [mmohrhard/crash#29]
Add adjustable time ranges for the main view. Suggestion:

- 3 days
- 7 days (default)
- 14 days
- 30 days (one month)

To get an idea, attached you find how mozilla solved this for firefox crash stats.
![ff crash stats](https://cloud.githubusercontent.com/assets/5708172/21072676/b50e19c0-beca-11e6-8022-b3a78fbab5e5.jpg)

This should come useful, since it allows to get a quick overview of how versions and crashes evolve.

**Comment by mmohrhard** [comment]
This can be easily added as we already have something similar.

https://github.com/mmohrhard/crash/blob/master/django/crashreport/stats/templates/stats/version.html#L20 already contains something like this for the version view.

So this requires to adapt the https://github.com/mmohrhard/crash/blob/master/django/crashreport/stats/templates/stats/main.html file with the corresponding template code and teach https://github.com/mmohrhard/crash/blob/master/django/crashreport/stats/views.py#L91 about the additional get parameter. Don't forget to add the parameter to the corresponding URLs.

**Comment by amitdaga** [comment]
@mmohrhard Have you assigned anyone for this task? I can take this up if this is still unassigned.

**Comment by foss-** [comment]
It pretty sure is unassigned

**Comment by mmohrhard** [comment]
Yes it is still unassigned.

**Comment by amitdaga** [comment]
#39 Setup would need some time. Will verify these changes after that.

**Comment by mmohrhard** [comment]
Thanks a lot for the patch. It has been merged and deployed to production.

For the setup current master has already some helpful code and can populate the DB with initial data through ./manage.py setup including a bit of data for the charts.

Are you interested in another simple task?

**Comment by amitdaga** [comment]
@mmohrhard Yes. Can have a look.
