### ISSUE TITLE
Add REST API for the chart data on the main page

### ISSUE THREAD

**Issue by mmohrhard** [mmohrhard/crash#31]
Currently the chart data is added to the html page statically during the template generation. Ideally we would have a REST API that exposes the chart data and load it through an call. That would also remove the need to rerender on the server side after implementing issue #29.

For this to work we need to replace the code in https://github.com/mmohrhard/crash/blob/master/django/crashreport/stats/views.py#L82 and fix the TODO in https://github.com/mmohrhard/crash/blob/master/django/crashreport/stats/views.py#L94.

The corresponding change in the template is necessary in https://github.com/mmohrhard/crash/blob/master/django/crashreport/stats/templates/stats/main.html#L12 where we currently just store the data statically during template processing.

**Comment by kaustubhmallik** [comment]
Hey, is this issue still open (just confirming)? If so, I would like to work on it? Is there a Contributor License Agreement or something which I get through. Waiting for you quick response :)

**Comment by mmohrhard** [comment]
Yes. It is still open.

We don't have a Contributor License Agreement. All files should have a MPL license header. If not please ping me and I'll add it. For any new file that you add you should add a MPL header as well.

**Comment by kaustubhmallik** [comment]
Sure, I started working on it. Will try to send a PR  as soon as possible. :)

**Comment by mestaritonttu** [comment]
Jan Iversen did some work on this. I guess it will appear in the commits soon. But it can be expanded to be more powerful.

**Comment by mmohrhard** [comment]
http://crashreport.libreoffice.org/api/get/crash-count provides the data necessary for the charts. This now needs integration into the javascript code for the charts.

**Comment by zeeshanabid94** [comment]
Is this still open?

**Comment by Liongold** [comment]
I guess this can be closed after that #40 has been merged.

**Comment by mmohrhard** [comment]
This has been implemented and deployed to the production instance.
