### ISSUE TITLE
Don't hard code the cgit link to LibreOffice 5.2

### ISSUE THREAD

**Issue by mmohrhard** [mmohrhard/crash#33]
Currently the link for the backtrace is always using the 5-2 target. See https://github.com/mmohrhard/crash/blob/master/django/crashreport/stats/static/stats/js/details.js#L26

We should instead take the version entry and use the correct version string dynamically.

The only problem is around something like 5.3.0.0 which maps to 5-3 and not 5-3-0.

**Comment by an0o0nym** [comment]
@mmohrhard I would like to take that one if possible.

**Comment by mmohrhard** [comment]
And merged into production. Thanks a lot for your work.
