### ISSUE TITLE
linkage to tdf BugZilla issues on Bugs tab

### ISSUE THREAD

**Issue by vsfoote** [mmohrhard/crash#34]
Just filed tdf#105097 via the http://crashreport.libreoffice.org instance, but the bug report is not being picked up on the "Bugs" tab of the UI.  I know I've seen linkages to bugs in past use of the service--has something broken?

=-ref-=
http://crashreport.libreoffice.org/stats/signature/ScTransferObj::~ScTransferObj()?page=1

**Comment by mmohrhard** [comment]
Fixed. This was a server configuration issue and not a code issue.
